const actionTypes = Object.freeze({
    GET_ALL_TECHIES: "GET_ALL_TECHIES",
    GET_APPROVED_TECHIES: "GET_APPROVED_TECHIES",
    GET_UNAPPROVED_TECHIES: "GET_UNAPPROVED_TECHIES",
    TOGGLE_ADD_EDIT_FORM: "TOGGLE_ADD_EDIT_FORM",
    ADD_NEW_TECHIE: "ADD_NEW_TECHIE",
    UPDATE_EXISTING_TECHIE: "UPDATE_EXISTING_TECHIE",
    APPROVE_TECHIE: "APPROVE_TECHIE"
});

export default actionTypes;